"""empty message

Revision ID: dbd5b210f9d6
Revises: 
Create Date: 2021-02-21 21:08:20.016828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd5b210f9d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_hub_countries', sa.Column('iso4217_currency_name', sa.String(length=80), nullable=True))
    op.drop_column('data_hub_countries', 'ISO4217_currency_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_hub_countries', sa.Column('ISO4217_currency_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('data_hub_countries', 'iso4217_currency_name')
    # ### end Alembic commands ###
