"""empty message

Revision ID: dc4d6476da70
Revises: 9842856aebe9
Create Date: 2021-03-08 20:50:31.782381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4d6476da70'
down_revision = '9842856aebe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secrets', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('secrets', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('secrets', 'why1',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secrets', 'why1',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('secrets', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('secrets', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
